server:
  port: 8084
spring:
  application:
    name: basket-service
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    properties:
      schema.registry.url: http://localhost:8081
    consumer:
      group-id: basket-service
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto.register.schemas: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      schema.registry.url: ${spring.kafka.properties.schema.registry.url}
      properties:
        specific.avro.reader: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      schema.registry.url: ${spring.kafka.properties.schema.registry.url}
      acks: all
      auto.register.schemas: true
      properties:
        enable.idempotence: true
    sleuth:
      opentracing:
        enabled: true
      sampler:
        probability: 1.0
      trace-id128: true

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus

topics:
  input:
    orders: order-status
  output:
    basket: basket-orders


