spring:
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers:127.0.0.1:9092}
    properties:
      schema.registry.url: mock://http://localhost:8081
    consumer:
      auto.register.schemas: true
    producer:
      auto.register.schemas: true